name: Failing Check Workflow
run-name: ${{ github.event.inputs.run_name }}

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Owner of the repository where the workflow is located'
        required: false
        default: '3'
      run_name:
        description: 'Name of the workflow run'
        required: false
        default: 'Failing Check Workflow Dispatched'

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Tanaguch Nap Trigger
        id: trigger
        uses: vtb-wanderers63/gha-tamaguchi-sleep-failure@main
        with:
          workflow_run_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.duration }}
